alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: until.design
  type: PRIMARY
  zone: until.design
- domain: www.until.design
  type: ALIAS
  zone: until.design
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: until-design-web
    match:
      path:
        prefix: /
name: until-design
region: nyc
services:
- name: until-design-web
  github:
    branch: main
    deploy_on_push: true
    repo: sharksandrobots/until.design
  build_command: npm install && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port $PORT
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: / 